### ISSUE TITLE
Rain sensor Data 

### ISSUE THREAD

**Issue by Salve87** [CestLaGalere/mobilealerts#1]
Hello, 
the integration works great.
I have a small issue with the Rain sensor:
In the App and at _https://measurements.mobile-alerts.eu/_ i get eg.: 0,5mm rain.
the HA integration shows me 990mm of rain.
I guess that is the sumup of all rain ever.
Can anybody help me or is having the same issue?
Best regards
![Bildschirmfoto 2023-01-04 um 13 43 56](https://user-images.githubusercontent.com/37770456/210558160-08eeab4d-0f35-4807-a84b-7aeb2fe1b8bb.png)
![Bildschirmfoto 2023-01-04 um 13 47 15](https://user-images.githubusercontent.com/37770456/210558239-6ec69fa7-c29c-4f15-8d3f-3a48098f3d51.png)

**Comment by CestLaGalere** [comment]
I believe the rain sensor shows the current total, I will look to see how to sort this within Home Assistant to read the previous value - ideally would look for rainfall since midnight?

**Comment by Rai2023** [comment]
Rainfall the last hour would be nice.

**Comment by petrleocompel** [comment]
For this is example - https://www.home-assistant.io/integrations/utility_meter/

You can create custom helper based on your preference. 
No need to implement on integration side.

**Comment by CestLaGalere** [comment]
closed as custom helper provides solution - see above (thanks @petrleocompel )
