### ISSUE TITLE
Temperature isn't updating

### ISSUE THREAD

**Issue by cetepek** [CestLaGalere/mobilealerts#10]
I have 2 temperature gauges, one of which stopped updating in home assistant. It seems that it hasn't updated for 12 hours even though mobile alerts shows the temperature has been changing continuously.

**Comment by cetepek** [comment]
I checked again and it seems that neither temperature data was updated.

**Comment by petrleocompel** [comment]
Any logs ? I received some testing configs so a will try today in evening if it is working.

**Comment by cetepek** [comment]
Didnt find anything from the logs that says "mobile alert"

**Comment by cetepek** [comment]
After rebooting everything seems to be working

**Comment by NorbertHoyer** [comment]
I have a similar issue. Out of 6 sensors 2 would not update.  Only the last 2 show a constant value, the others are fine.

**Comment by petrleocompel** [comment]
Are you sure you have no problem with "multiple entities" like entity named almost similar but `_1` on end ?
@NorbertHoyer 

Also restart + logs? Anything to catch on?

**Comment by NorbertHoyer** [comment]
I changed the sequence of the sensors and now it works.
Thanks!

**Comment by cetepek** [comment]
I noticed yesterday that if I restart home assistant and there is a some kind of delay or server outage on mobile alerts servers, the sensors wont update until you restart home assistant again.

**Comment by show2go** [comment]
> I noticed yesterday that if I restart home assistant and there is a some kind of delay or server outage on mobile alerts servers, the sensors wont update until you restart home assistant again.

Hi All,
for me the same... everyday, some hours of data lost, it comes back by itself, but when i restart its immediately back... 
thx

**Comment by NorbertHoyer** [comment]
Same here, it drops out almost everyday now, but when I restart it's back. Any idea how this could be improved?

**Comment by Maddin1684** [comment]
Same her, too. 
Temp isnt updating, but kable sensor and humidity works well.

**Comment by petrleocompel** [comment]
Please try current version there were some fixes.

**Comment by petrleocompel** [comment]
duplicates with #16 
Fixed in [v1.2.2](https://github.com/CestLaGalere/mobilealerts/releases/tag/v1.2.2)
Please report to #16 with logs in any case
