### ISSUE TITLE
2024.1.2 - Platform error: sensor - Integration 'mobile_alerts' not found. 

### ISSUE THREAD

**Issue by ilwalti** [CestLaGalere/mobilealerts#12]
mobilealerts worked fine upto 2024.1.1
Just updated to 2024.1.2 and I've got this error:

Logger: homeassistant.config
Source: config.py:1258
First occurred: 17:29:35 (1 occurrences)
Last logged: 17:29:35

Platform error: sensor - Integration 'mobile_alerts' not found.

A complete restart of HA doesn't help and in "check and restart" page the error message is
- Configuration warnings
- Platform error 'sensor' from integration 'mobile_alerts' - Integration 'mobile_alerts' not found.

Any ideas? I've seen that other people have some troubles. See https://community.home-assistant.io/t/2024-1-happy-automating/665947/181?page=9

**Comment by petrleocompel** [comment]
Context error from linked issue
```
File “/usr/src/homeassistant/homeassistant/helpers/entity_platform.py”, line 360, in _async_setup_platform
await asyncio.shield(task)
File “/config/custom_components/mobile_alerts/binary_sensor.py”, line 234, in async_setup_entry
async_add_entities(create_gateway_binary_sensor_entities(coordinator.gateway))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/config/custom_components/mobile_alerts/binary_sensor.py”, line 190, in create_gateway_binary_sensor_entities
return [
^
File “/config/custom_components/mobile_alerts/binary_sensor.py”, line 191, in
MobileAlertesGatewayBinarySensor(
File “/config/custom_components/mobile_alerts/binary_sensor.py”, line 79, in init
description.translation_key = description.key
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “”, line 4, in setattr
dataclasses.FrozenInstanceError: cannot assign to field ‘translation_key’
2024-01-04 17:53:02.974 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/helpers/entity_platform.py”, line 360, in _async_setup_platform
await asyncio.shield(task)
File “/config/custom_components/mobile_alerts/sensor.py”, line 508, in async_setup_entry
async_add_entities(create_gateway_sensor_entities(coordinator.gateway))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/config/custom_components/mobile_alerts/sensor.py”, line 455, in create_gateway_sensor_entities
return [
^
File “/config/custom_components/mobile_alerts/sensor.py”, line 456, in
MobileAlertesGatewaySensor(
File “/config/custom_components/mobile_alerts/sensor.py”, line 161, in init
description.translation_key = description.key
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “”, line 4, in setattr
dataclasses.FrozenInstanceError: cannot assign to field ‘translation_key’
```

**Comment by ilwalti** [comment]
FYI, at the moment sensors are back... after about 6 hours of blackout. But in the meantime I was able to retrieve all values via curl.

**Comment by petrleocompel** [comment]
You need to rename the `mobile_alerts` to `mobilealerts`

It is even in readme that this is correct configuration. 

It was needed to match logos provided by homeassistant

**Comment by petrleocompel** [comment]
What version of integration do you use? 
And any startup logs?

**Comment by petrleocompel** [comment]
I will test later with ha 2024.

**Comment by gianb80** [comment]
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:360
Integration: Sensore binario (documentation, issues)
First occurred: 12:48:14 (5 occurrences)
Last logged: 13:25:48

Error while setting up mobile_alerts platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 234, in async_setup_entry
    async_add_entities(create_gateway_binary_sensor_entities(coordinator.gateway))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 190, in create_gateway_binary_sensor_entities
    return [
           ^
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 191, in <listcomp>
    MobileAlertesGatewayBinarySensor(
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 79, in __init__
    description.translation_key = description.key
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'translation_key'

**Comment by gianb80** [comment]
I'm using this: https://github.com/PlusPlus-ua/ha_mobilealerts

**Comment by petrleocompel** [comment]
> I'm using this: https://github.com/PlusPlus-ua/ha_mobilealerts

That is acting as proxy server.
This integration is reading values from cloud.

**Comment by ilwalti** [comment]
Nope, it wasn't me. I've reported the right one, some other people referred to the other.
Cheers.

**Comment by petrleocompel** [comment]
@ilwalti Can you provide logs and config ?

**Comment by ilwalti** [comment]
No, sorry. As I wrote 3 day ago, after 6 hours the problem was solved, and now the values are flowing in HA.
There was some glitches, but I can't state the cause...
I think you can close the issue for now.
