### ISSUE TITLE
LENGTH_MILLIMETERS should be changed to UnitOfLength.MILLIMETERS (at least for HA 2025.1)

### ISSUE THREAD

**Issue by helmut-hackl** [CestLaGalere/mobilealerts#14]
`LENGTH_MILLIMETERS` was used from mobile_alerts, this is a deprecated constant which will be removed in HA Core 2025.1. Use `UnitOfLength.MILLIMETERS` instead

**Comment by petrleocompel** [comment]
Fixed in [v1.2.1](https://github.com/CestLaGalere/mobilealerts/releases/tag/v1.2.1)
