### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MichaelS1955** [CestLaGalere/mobilealerts#18]
Hi, 
maybe I am too stupid ;-)
I installed mobilealerts as described.
I have added these lines to my sensors.yaml and I restarted HA.
But I do not see one of the defined devices. 
What  is wrong? Where do I find them? Is it not necessary to enter the IP-adress of the gateway?

Regards Michael
---------------------------------------------
#Mobile Alerts / Dustmann
  - platform: mobile_alerts
    phone_id: 0123456789
    devices:
      - device_id: 0844999DF095
        name: Regensensor Garten
        type: r
      - device_id: 0358957DD926
        name: Temperatur Gartenhaus
        type: t1
      - device_id: 0358957DD926
        name: Luftfeuchtigkeit Gartenhaus
        type: h1

**Comment by petrleocompel** [comment]
Your devices are reporting to cloud correctly
```
curl -d "{'deviceids': '0358957DD926'}" -H "Content-Type: application/json" https://www.data199.com/api/pv1/device/lastmeasurement

{
  "devices": [
    {
      "deviceid": "0358957DD926",
      "lastseen": 1706275297,
      "lowbattery": false,
      "measurement": {
        "idx": 228537,
        "ts": 1706275291,
        "c": 1706275297,
        "lb": false,
        "t1": 7.6,
        "h": 82.0
      }
    }
  ],
  "success": true
}
```

Please check logs of HA. Otherwise you should find "entities" named by provided names. Not devices.

**Comment by MichaelS1955** [comment]
Thank you.I found them under entities
