### ISSUE TITLE
Yaml configuration

### ISSUE THREAD

**Issue by SuperMesna** [CestLaGalere/mobilealerts#2]
Hey,

I am new to home assistant, so this might be a silly question, sorry about that.
You write "add elements to yaml sensor section:"
where can I find this section? Is this developer tools/states/sensor.hacs ?

**Comment by Rai2023** [comment]
Add it to sensor.yaml
I did it, but don´t know what´s next....

**Comment by petrleocompel** [comment]
To answer your questions guys. @SuperMesna @Rai2023 

https://www.home-assistant.io/docs/configuration/
https://www.home-assistant.io/docs/configuration/yaml/

Basically you have to edit a file where you will place the configuration, valid syntax. Save and restart HomeAssistant.
Then this integration would load and provide data.

**Comment by CestLaGalere** [comment]
Closing as this is a question about configuration.yaml
