### ISSUE TITLE
HA 2024.4 Sensor not avaiable

### ISSUE THREAD

**Issue by Maddin1684** [CestLaGalere/mobilealerts#24]
After the Update 2024.4 the sensors don’t show up. 

When I downgrade to 2024.3.3 everything works fine.

**Comment by petrleocompel** [comment]
@Maddin1684 It seems fine with 2024.4.2.

Can you provide logs ?

**Comment by Maddin1684** [comment]
It works fine with 2024.4.2‘

**Comment by petrleocompel** [comment]
👍
