### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by N3m3515** [CestLaGalere/mobilealerts#27]
The Integration is no longer showing entities.
There are no errors in the Log but it seems to no longer work

**Comment by CestLaGalere** [comment]
Still working correctly on my system - unfortunately you have provided no other details so we cannot help until we have anything more - narrow it down to what you did just before it stopped working?

**Comment by N3m3515** [comment]
Well thats the thing. I did nothing. It worked a week ago and now every Entity is no longer available

I can share my config:

sensor:
  - platform: mobile_alerts
    phone_id: 123456789012
    devices:
      - device_id: 0B6B1288E823
        name: Wind Speed
        type: ws
      - device_id: 0B6B1288E823
        name: Wind direction raw
        type: wd
      - device_id: 03054542A811
        name: Outside Humidity
        type: h
      - device_id: 03054542A811
        name: Humidity 3H
        type: h3havg
      - device_id: 03054542A811
        name: Humidity 24H
        type: h24havg
      - device_id: 03054542A811
        name: Outside Temperature
        type: t1
      - device_id: 080A7EA0E0A2
        name: Rain
        type: r

template:
  - sensor:
        - name: Wind Direction
          state: >
           {%- set wd = {
             '0': 'N',
             '1': 'NNE',
             '2': 'NE',
             '3': 'ENE',
             '4': 'E',
             '5': 'ESE',
             '6': 'SE',
             '7': 'SSE',
             '8': 'S',
             '9': 'SSW',
             '10': 'SW',
             '11': 'WSW',
             '12': 'W',
             '13': 'WNW',
             '14': 'NW',
             '15': 'NNW'} -%}
           {%- set state = states('sensor.wind_direction') -%}
           {{ wd[state] if state in wd else state }}

**Comment by CestLaGalere** [comment]
I have added the first 2 entities on my system:
the start of my weather.yaml reads:

```
  - platform: mobile_alerts
    devices:
      - device_id: 0B6B1288E823
        name: N3 Wind Speed
        type: ws
      - device_id: 0B6B1288E823
        name: N3 Wind direction raw
        type: wd
```
they show up correctly and are showing values of 0.9 and 11
So I assume that it is something else in your configuration...
(the phone_id is optional - if you set up rules it can return the data but we don't do anything with this)

**Comment by N3m3515** [comment]
I deleted it from my config, restarted, added it again and restarted again. Now everything is working again.
must have been a formating error somewhere

**Comment by CestLaGalere** [comment]
Closed - user error
(and not a please or thank you in sight - so glad to have helped)
